# Generated by Django 4.2.4 on 2023-09-04 21:12

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_creditor', models.BooleanField(choices=[(False, 'Debtor'), (True, 'Creditor')])),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expenses'), ('ASS', 'Assets'), ('EQU', 'Equity'), ('LIA', 'Liabilities')], max_length=3)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EntriesRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to=books.models.upload_path)),
                ('value', models.DecimalField(decimal_places=2, max_digits=99)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.entries')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.ledger')),
            ],
        ),
    ]
