# Generated by Django 4.2.4 on 2023-09-12 20:02

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document', models.FileField(blank=True, upload_to=books.models.upload_path)),
                ('value', models.DecimalField(decimal_places=2, max_digits=99)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense'), ('CAS', 'Cash'), ('GEN', 'General')], max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entriesrow',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entriesrow',
            name='ledger',
        ),
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.DeleteModel(
            name='EntriesRow',
        ),
        migrations.AddField(
            model_name='entryrow',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.ledger'),
        ),
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.journal'),
        ),
    ]
