# Generated by Django 4.2.4 on 2023-09-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_entryrow_ledger_delete_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryrow',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryrow',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='EntryRow',
        ),
    ]
