# Generated by Django 4.2.4 on 2023-09-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_entryrow_entry_remove_entryrow_ledger_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
