# Generated by Django 4.2.4 on 2023-09-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_journal'),
        ('books', '0005_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
