# Generated by Django 4.2.4 on 2023-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_creditor', models.BooleanField(choices=[(False, 'Debtor'), (True, 'Creditor')])),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
