# Generated by Django 4.2.4 on 2023-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expenses'), ('ASS', 'Assets'), ('EQU', 'Equity'), ('LIA', 'Liabilities')], max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
