FROM docker.io/python:3.12

RUN apt-get update && apt-get upgrade -y && apt-get install sudo -y

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY ./requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY ./app /app

WORKDIR /app

EXPOSE 8000

RUN rm -r /var/cache/apt/archives

RUN useradd accountancpy -s /bin/bash -G sudo

USER accountancpy:accountancpy

ENTRYPOINT [ "python", "-Wa", "manage.py", "runserver", "0.0.0.0:8000" ]
