# Generated by Django 4.2.4 on 2023-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense'), ('CAS', 'Cash'), ('GEN', 'General')], max_length=3)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
