# Generated by Django 4.2.4 on 2023-09-23 15:39

import app.settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        ('books', '0004_remove_entryrow_entry_remove_entryrow_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.journal')),
            ],
        ),
        migrations.CreateModel(
            name='EntryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('document', models.FileField(blank=True, upload_to=app.settings.upload_path)),
                ('value', models.DecimalField(decimal_places=2, max_digits=99)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgers.ledger')),
            ],
        ),
    ]
