# Generated by Django 4.2.4 on 2023-09-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('entries', '0002_entryrow_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrow',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
