# Generated by Django 4.2.4 on 2023-09-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('entries', '0003_alter_entryrow_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journals.journal'),
        ),
    ]
