# Generated by Django 4.2.4 on 2023-10-16 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('entries', '0005_alter_entryrow_date'), ('entries', '0006_alter_entryrow_date')]

    dependencies = [
        ('entries', '0004_alter_entry_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrow',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entryrow',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
