# Generated by Django 4.2.4 on 2023-10-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entryrow_date_squashed_0006_alter_entryrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrow',
            name='date',
            field=models.DateField(),
        ),
    ]
