# Generated by Django 5.0.1 on 2024-01-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_alter_entryrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrow',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
